### ISSUE TITLE
Tag 2.0.0 to support the Short Range Weather App public release

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [ufs-community/UFS_UTILS#351]
Create a tag from the release branch at 5f71127 to support the first public release of the SRW App.  The agreed upon tag name will be `ufs-v2.0.0`

**Comment by GeorgeGayno-NOAA** [comment]
The documentation was successfully updated: https://noaa-emcufs-utils.readthedocs.io/en/ufs-v2.0.0/

**Comment by edwardhartnett** [comment]
Let's do a proper release instead of just a tag.

I'll take you through the steps tomorrow.

**Comment by JeffBeck-NOAA** [comment]
@edwardhartnett, just an FYI that we're identifying the repositories through tags in the ufs-srweather-app release branch Externals.cfg file, so we will need to have the tag that @GeorgeGayno-NOAA created.  No reason we can't also create a release as well, though!

**Comment by climbfuji** [comment]
@edwardhartnett we should wait until the final testing is completed. There is always a possibility that we have to retag. Once the SRw App release is announced, the releases for UFS_UTILS etc can be created.

**Comment by edwardhartnett** [comment]
Releases have tags and we don't have to change it. Releases also have release announcements, published tarballs, documentation changes, and changes to the project management screens. ;-)

@GeorgeGayno-NOAA I am surprised that we went from 1.0.0 to 2.0.0 but that's cool. What is the next release going to be? 2.1? Or 3.0?

**Comment by climbfuji** [comment]
> Releases have tags and we don't have to change it. Releases also have release announcements, published tarballs, documentation changes, and changes to the project management screens. ;-)
> 
> @GeorgeGayno-NOAA I am surprised that we went from 1.0.0 to 2.0.0 but that's cool. What is the next release going to be? 2.1? Or 3.0?

I know this is confusing, but this release is different because it is from a different branch (release/public-v2), specifically for the UFS SRW (Short Range Weather App) public release, and does not align with the release numbers that are used by hpc stack etc. We have this problem with all repositories. The release is `ufs-v2.0.0` as opposed to just `vM.N.R` for the releases used by hpc-stack.

We had two such releases in the past `ufs-v1.0.0` and `ufs-v1.1.0`, both from the release branch `release/public-v1`, for the Medium-Range Weather App (MRW) public release v1.0.0 and v.1.1.0 .

**Comment by edwardhartnett** [comment]
OK, that is confusing.

**Comment by climbfuji** [comment]
> OK, that is confusing.

Otherwise it would be too easy.
