### ISSUE TITLE
in chgres_cube, stop setting flag -fconvert=big-endian

### ISSUE THREAD

**Issue by edwardhartnett** [ufs-community/UFS_UTILS#470]
in chgres_cube, why are we setting flag -fconvert=big-endian?

According to GNU documentation:
https://gcc.gnu.org/onlinedocs/gfortran/CONVERT-specifier.html

> -fconvert=conversion
> Specify the representation of data for unformatted files. Valid values for conversion are: ‘native’, the default; ‘swap’, swap between big- and little-endian; ‘big-endian’, use big-endian representation for unformatted files; ‘little-endian’, use little-endian representation for unformatted files.

Does chgres_cube write unformatted data?

**Comment by GeorgeGayno-NOAA** [comment]
No it does not. I can remove it. I can check for that flag thru the entire repo.

**Comment by edwardhartnett** [comment]
OK, let's get 1.3.0 out and we can do this...

**Comment by spencerkclark** [comment]
I have found that the assumption of endianness is important when reading old-style GFS analysis data in the sfcio and sigio formats (e.g. with `input_type="gfs_sigio"`).  With UFS-UTILS version 1.9 I have found on a little endian system that `chgres_cube` cannot properly read these data files, because it uses the native byte order when reading them (the symptom of this is that the headers return nonsense values and so the sfcio and sigio libraries do not know how to interpret them).  When calling `chgres_cube` I get an error like this:
```
 - DEFINE INPUT GRID OBJECT FOR GAUSSIAN DATA.
 - OPEN AND READ /input_data/gfs.t00z.sfcanl
 - DEFINE INPUT GRID OBJECT FOR GAUSSIAN DATA.
 - OPEN AND READ /input_data/gfs.t00z.sfcanl
 - FATAL ERROR: READING FILE
 - IOSTAT IS:           -2
 - FATAL ERROR: READING FILE
 - IOSTAT IS:           -2
Abort(999) on node 1 (rank 1 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 999) - process 1
 - DEFINE INPUT GRID OBJECT FOR GAUSSIAN DATA.
 - OPEN AND READ /input_data/gfs.t00z.sfcanl
Abort(999) on node 2 (rank 2 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 999) - process 2
 - FATAL ERROR: READING FILE
 - IOSTAT IS:           -2
Abort(999) on node 3 (rank 3 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 999) - process 3
+ iret=231
+ '[' 231 -ne 0 ']'
+ echo 'FATAL ERROR RUNNING CHGRES'
FATAL ERROR RUNNING CHGRES
+ exit 231
```
which stems from the fact that [the sfcio library reads in a value of `1024393984` for `head%ivs`](https://github.com/NOAA-EMC/NCEPLIBS-sfcio/blob/95312a5be1b028c549114a642e0b5b6271920bf4/src/sfcio_module.f#L573), which is a value it does not understand (the value it should read in this case is `200509`).

If I override the endianness assumption (in the case of my compiler) by exporting `GFORTRAN_CONVERT_UNIT=big_endian` at runtime ([documentation link](https://gcc.gnu.org/onlinedocs/gcc-4.2.4/gfortran/GFORTRAN_005fCONVERT_005fUNIT.html)) then I am able to read the files properly, and `chgres_cube` runs to completion.  It took some work to track down the source of the issue and find a solution, however.  Would retaining the compile-time flags discussed in this issue have helped in this instance?  They are present in the `CMakeLists.txt` files for the [sfcio](https://github.com/NOAA-EMC/NCEPLIBS-sfcio/blob/95312a5be1b028c549114a642e0b5b6271920bf4/src/CMakeLists.txt#L11) and [sigio](https://github.com/NOAA-EMC/NCEPLIBS-sigio/blob/272e0b1344869d58ad9b6f364f3e6d8440ac92c4/src/CMakeLists.txt#L7) libraries, but seem to have no effect in this case, because according to [this documentation](https://gcc.gnu.org/onlinedocs/gcc-4.2.4/gfortran/Runtime-Options.html#Runtime-Options), what matters is whether they are applied when compiling the program one is actually running (i.e. "This option has an effect only when used in the main program.").

**Comment by edwardhartnett** [comment]
OK, so it sounds like chgres_cube does read unformatted data files...

**Comment by spencerkclark** [comment]
Thanks, yes, a bit of an old format, but it’s great that `chgres_cube` can still support it.
