### ISSUE TITLE
Fix filter_topo so it uses actual resolution (e.g. in kilometers) to set filtering parameters, not number of grid points

### ISSUE THREAD

**Issue by gsketefian** [ufs-community/UFS_UTILS#548]
The filtering parameters in filter_topo are set according to number of grid points, not actual grid resolution (e.g. in kilometers).  For this reason, a regional ESG grid with 100 grid points on a side that covers a domain of 300km on a side (so that delx=3km) will get the same filtering parameters as another ESG grid with 100 points but that covers a domain of 3000km on a side (so that delx=30km).

The filtering parameters seems to have been tuned for a global UNIFORM cubed-sphere grid.  For a stretched cubed-sphere grid (global or regional), the code calculates a uniform-grid equivalent number of grid points (mdim) from the actual number of grid points (npx or npx_global).  This is a start, but for a cubed-sphere-based grid (global or regional), it must also take into account refine_ratio, which it doesn't.  For a regional ESG grid, it can end up using completely inappropriate filtering parameter values because stretch_fac and refine_ratio are not defined for such a grid, and setting filtering parameters based on number of grid points is in general incorrect for such a grid.

The best way to fix both of these issues is to set the filtering parameters based on actual grid size (in kilometers).

**Comment by gsketefian** [comment]
@GeorgeGayno-NOAA @JacobCarley-NOAA Who would be the best person to handle this issue?

**Comment by GeorgeGayno-NOAA** [comment]
Some additional thoughts from @gsketefian from his recent email

_The upshot was that maybe we should move the global_equiv_resol code into the topo code so that what you pass into the topo code is a grid size (in meters, probably) instead of number of grid points.  That way we don't have to go through the steps of first calculating the global_equiv_resol in the SRW scripts, we just pass in the (average?) grid size to the topo grid._

**Comment by JeffBeck-NOAA** [comment]
Based on email discussions with @gsketefian, it sounds like through the combination of global_equiv_resol and filter_topo, the topography filtering is working as expected for non-stretched/refined grids.  Since the SRW/MRW and HAFS Apps don't use stretched grids, there is no immediate concern to implement any changes to how the topography filtering works.  If at some point in the future, we need to generate an average grid size for filtering of a refined grid, we can implement Gerard's suggestion, highlighted by @GeorgeGayno-NOAA above.  I'll go ahead and close this issue for now.

**Comment by gsketefian** [comment]
@JeffBeck-NOAA To clarify about the SRW, the both the `GFDLgrid` and `ESGgrid` types of grids are non-uniform grids (so they are stretched at least a little bit even if you specify no stretching, although `ESGgrid` much less stretched than `GFDLgrid`).  Regardless of if you use a stretched or unstretched `GFDLgrid` or an `ESGgrid`, the workflow will call `global_equiv_resol` to calculate the grid parameters (specifically, the `CRES,` which is the number of grid points along one side of a tile) for a global cubed sphere grid to that matches the average grid size of the regional `GFDLgrid` or `ESGgrid` and then use that `CRES` (along with `stretch_fac=1` and `refine_ratio=1`) to calculate the topography filtering parameters.  

What I'm really looking to do is rewrite `filter_topo` so you pass it some grid size (e.g. the average grid size of a regional grid), and it does this global equivalent resolution calculation internally, uses the result to calculate the filtering parameters, and uses those to do the filtering.  That way, the SRW and other apps don't have to do the `global_equiv_resol` calculation in their scripts; it all gets done internally within `filter_topo`.  This requires moving the `global_equiv_resol` code into `filter_topo`.

It's not urgent, but the current approach in the SRW (and maybe the HAFS) is confusing, and this issue has been around for a while now.  So it would be nice to take care of it.
